### PR TITLE
Update creation.lua [ Fix Error : handler (@PolyZone/creation/server/…

### PR DESCRIPTION
**Pull request by subhampro**
…creation.lua:22]

This error coming because of latest Artifacts !!!

09:41:45 AM [     script:PolyZone] SCRIPT ERROR: @PolyZone/creation/server/creation.lua:22: attempt to call a nil value (field 'output')
09:41:45 AM [     script:PolyZone] > handler (@PolyZone/creation/server/creation.lua:22)

Fixed !!!

> This code uses LoadResourceFile to read the existing content of the file and SaveResourceFile to save the updated content, ensuring that the file operations are handled correctly in the FiveM environment.

### CODE REVIEW

**Comment by KelloTV** [comment]
This fix still is not working for me

**Comment by subhampro** [comment]
@KelloTV Please check now I fixed All of the Bugs now It wwill create TXT file inside your Script PolyZone Folder!

**Comment by subhampro** [comment]
@KelloTV  Please Check my latest Pull Request !

https://github.com/mkafrin/PolyZone/pull/111

**Comment by KelloTV** [comment]
@subhampro Thanks bro, will do

**Comment by KelloTV** [comment]
@subhampro Still getting error. Passed points table with less than 3 points to PoluZone:Create()

**Pull request closed without merging**
